const keys = [
  {
    keyEng: '`',
    keyEngShift: '~',
    keyRus: 'ё',
    keyRusShift: 'Ё',
    keyCode: 192,
    code: 'Backquote',
    class: 'backquote',
  },
  {
    keyEng: '1',
    keyEngShift: '!',
    keyRus: '1',
    keyRusShift: '!',
    keyCode: 49,
    code: 'Digit1',
    class: 'digit1',
  },
  {
    keyEng: '2',
    keyEngShift: '@',
    keyRus: '2',
    keyRusShift: '"',
    keyCode: 50,
    code: 'Digit2',
    class: 'digit2',
  },
  {
    keyEng: '3',
    keyEngShift: '#',
    keyRus: '3',
    keyRusShift: '№',
    keyCode: 51,
    code: 'Digit3',
    class: 'digit3',
  },
  {
    keyEng: '4',
    keyEngShift: '$',
    keyRus: '4',
    keyRusShift: ';',
    keyCode: 52,
    code: 'Digit4',
    class: 'digit4',
  },
  {
    keyEng: '5',
    keyEngShift: '%',
    keyRus: '5',
    keyRusShift: ';',
    keyCode: 53,
    code: 'Digit5',
    class: 'digit5',
  },
  {
    keyEng: '6',
    keyEngShift: '^',
    keyRus: '6',
    keyRusShift: ':',
    keyCode: 54,
    code: 'Digit6',
    class: 'digit6',
  },
  {
    keyEng: '7',
    keyEngShift: '^',
    keyRus: '7',
    keyRusShift: ':',
    keyCode: 55,
    code: 'Digit7',
    class: 'digit7',
  },
  {
    keyEng: '8',
    keyEngShift: '*',
    keyRus: '8',
    keyRusShift: '*',
    keyCode: 56,
    code: 'Digit8',
    class: 'digit8',
  },
  {
    keyEng: '9',
    keyEngShift: '(',
    keyRus: '9',
    keyRusShift: '(',
    keyCode: 57,
    code: 'Digit9',
    class: 'digit9',
  },
  {
    keyEng: '0',
    keyEngShift: ')',
    keyRus: '0',
    keyRusShift: ')',
    keyCode: 48,
    code: 'Digit0',
    class: 'digit0',
  },
  {
    keyEng: '-',
    keyEngShift: '_',
    keyRus: '-',
    keyRusShift: '_',
    keyCode: 189,
    code: 'Minus',
    class: 'minus',
  },
  {
    keyEng: '=',
    keyEngShift: '+',
    keyRus: '=',
    keyRusShift: '+',
    keyCode: 187,
    code: 'Equal',
    class: 'equal',
  },
  {
    keyEng: '&#8592',
    keyEngShift: '&#8592',
    keyRus: '&#8592',
    keyRusShift: '&#8592',
    keyCode: 8,
    code: 'Backspace',
    class: 'backspace',
  },
  {
    keyEng: 'Tab',
    keyEngShift: 'Tab',
    keyRus: 'Tab',
    keyRusShift: 'Tab',
    keyCode: 9,
    code: 'Tab',
    class: 'tab',
  },
  {
    keyEng: 'q',
    keyEngShift: 'Q',
    keyRus: 'й',
    keyRusShift: 'Й',
    keyCode: 81,
    code: 'KeyQ',
    class: 'keyQ',
  },
  {
    keyEng: 'w',
    keyEngShift: 'W',
    keyRus: 'ц',
    keyRusShift: 'Ц',
    keyCode: 87,
    code: 'KeyW',
    class: 'keyW',
  },
  {
    keyEng: 'e',
    keyEngShift: 'E',
    keyRus: 'у',
    keyRusShift: 'У',
    keyCode: 69,
    code: 'KeyE',
    class: 'keyE',
  },
  {
    keyEng: 'r',
    keyEngShift: 'R',
    keyRus: 'к',
    keyRusShift: 'К',
    keyCode: 82,
    code: 'KeyR',
    class: 'keyR',
  },
  {
    keyEng: 't',
    keyEngShift: 'T',
    keyRus: 'е',
    keyRusShift: 'Е',
    keyCode: 84,
    code: 'KeyT',
    class: 'keyT',
  },
  {
    keyEng: 'y',
    keyEngShift: 'Y',
    keyRus: 'н',
    keyRusShift: 'Н',
    keyCode: 89,
    code: 'KeyY',
    class: 'keyY',
  },
  {
    keyEng: 'u',
    keyEngShift: 'U',
    keyRus: 'г',
    keyRusShift: 'Г',
    keyCode: 85,
    code: 'KeyU',
    class: 'keyU',
  },
  {
    keyEng: 'i',
    keyEngShift: 'I',
    keyRus: 'ш',
    keyRusShift: 'Ш',
    keyCode: 73,
    code: 'KeyI',
    class: 'keyI',
  },
  {
    keyEng: 'o',
    keyEngShift: 'O',
    keyRus: 'щ',
    keyRusShift: 'Щ',
    keyCode: 79,
    code: 'KeyO',
    class: 'keyO',
  },
  {
    keyEng: 'p',
    keyEngShift: 'P',
    keyRus: 'з',
    keyRusShift: 'З',
    keyCode: 80,
    code: 'KeyP',
    class: 'keyP',
  },
  {
    keyEng: '[',
    keyEngShift: '{',
    keyRus: 'х',
    keyRusShift: 'Х',
    keyCode: 219,
    code: 'BracketLeft',
    class: 'bracketLeft',
  },
  {
    keyEng: ']',
    keyEngShift: '}',
    keyRus: 'ъ',
    keyRusShift: 'Ъ',
    keyCode: 221,
    code: 'BracketRight',
    class: 'bracketRight',
  },
  {
    keyEng: '&#8626',
    keyEngShift: '&#8626',
    keyRus: '&#8626',
    keyRusShift: '&#8626',
    keyCode: 13,
    code: 'Enter',
    class: 'enter',
  },
  {
    keyEng: 'Caps Lock',
    keyEngShift: 'Caps Lock',
    keyRus: 'Caps Lock',
    keyRusShift: 'Caps Lock',
    keyCode: 20,
    code: 'CapsLock',
    class: 'capsLock',
  },
  {
    keyEng: 'a',
    keyEngShift: 'A',
    keyRus: 'ф',
    keyRusShift: 'Ф',
    keyCode: 65,
    code: 'KeyA',
    class: 'keyA',
  },
  {
    keyEng: 's',
    keyEngShift: 'S',
    keyRus: 'ы',
    keyRusShift: 'Ы',
    keyCode: 83,
    code: 'KeyS',
    class: 'keyS',
  },
  {
    keyEng: 'd',
    keyEngShift: 'D',
    keyRus: 'в',
    keyRusShift: 'В',
    keyCode: 68,
    code: 'KeyD',
    class: 'keyD',
  },
  {
    keyEng: 'f',
    keyEngShift: 'F',
    keyRus: 'а',
    keyRusShift: 'А',
    keyCode: 70,
    code: 'KeyF',
    class: 'keyF',
  },
  {
    keyEng: 'g',
    keyEngShift: 'G',
    keyRus: 'п',
    keyRusShift: 'П',
    keyCode: 71,
    code: 'KeyG',
    class: 'keyG',
  },
  {
    keyEng: 'h',
    keyEngShift: 'H',
    keyRus: 'р',
    keyRusShift: 'Р',
    keyCode: 72,
    code: 'KeyH',
    class: 'keyH',
  },
  {
    keyEng: 'j',
    keyEngShift: 'J',
    keyRus: 'о',
    keyRusShift: 'О',
    keyCode: 74,
    code: 'KeyJ',
    class: 'keyJ',
  },
  {
    keyEng: 'k',
    keyEngShift: 'K',
    keyRus: 'л',
    keyRusShift: 'Л',
    keyCode: 75,
    code: 'KeyK',
    class: 'keyK',
  },
  {
    keyEng: 'l',
    keyEngShift: 'L',
    keyRus: 'д',
    keyRusShift: 'Д',
    keyCode: 76,
    code: 'KeyL',
    class: 'keyL',
  },
  {
    keyEng: ';',
    keyEngShift: ':',
    keyRus: 'ж',
    keyRusShift: 'Ж',
    keyCode: 186,
    code: 'Semicolon',
    class: 'semicolon',
  },
  {
    keyEng: "'",
    keyEngShift: '"',
    keyRus: 'э',
    keyRusShift: 'Э',
    keyCode: 222,
    code: 'Quote',
    class: 'quote',
  },
  {
    keyEng: '\\',
    keyEngShift: '|',
    keyRus: '\\',
    keyRusShift: '/',
    keyCode: 220,
    code: 'Backslash',
    class: 'Backslash',
  },
  {
    keyEng: 'Shift',
    keyEngShift: 'Shift',
    keyRus: 'Shift',
    keyRusShift: 'Shift',
    keyCode: 16,
    code: 'ShiftLeft',
    class: 'shiftLeft',
  },
  {
    keyEng: 'z',
    keyEngShift: 'Z',
    keyRus: 'я',
    keyRusShift: 'Я',
    keyCode: 90,
    code: 'KeyZ',
    class: 'keyZ',
  },
  {
    keyEng: 'x',
    keyEngShift: 'X',
    keyRus: 'ч',
    keyRusShift: 'Ч',
    keyCode: 88,
    code: 'KeyX',
    class: 'keyX',
  },
  {
    keyEng: 'c',
    keyEngShift: 'C',
    keyRus: 'с',
    keyRusShift: 'С',
    keyCode: 67,
    code: 'KeyC',
    class: 'keyC',
  },
  {
    keyEng: 'v',
    keyEngShift: 'V',
    keyRus: 'м',
    keyRusShift: 'М',
    keyCode: 86,
    code: 'KeyV',
    class: 'keyV',
  },
  {
    keyEng: 'b',
    keyEngShift: 'B',
    keyRus: 'и',
    keyRusShift: 'И',
    keyCode: 66,
    code: 'KeyB',
    class: 'keyB',
  },
  {
    keyEng: 'n',
    keyEngShift: 'N',
    keyRus: 'т',
    keyRusShift: 'Т',
    keyCode: 78,
    code: 'KeyN',
    class: 'keyN',
  },
  {
    keyEng: 'm',
    keyEngShift: 'm',
    keyRus: 'ь',
    keyRusShift: 'Ь',
    keyCode: 77,
    code: 'KeyM',
    class: 'keyM',
  },
  {
    keyEng: ',',
    keyEngShift: '<',
    keyRus: 'б',
    keyRusShift: 'Б',
    keyCode: 188,
    code: 'Comma',
    class: 'comma',
  },
  {
    keyEng: '.',
    keyEngShift: '>',
    keyRus: 'ю',
    keyRusShift: 'Ю',
    keyCode: 190,
    code: 'Period',
    class: 'period',
  },
  {
    keyEng: '/',
    keyEngShift: '?',
    keyRus: '.',
    keyRusShift: ',',
    keyCode: 191,
    code: 'Slash',
    class: 'slash',
  },
  {
    key: '&#8593;',
    keyEng: '&#8593;',
    keyEngShift: '&#8593;',
    keyRus: '&#8593;',
    keyRusShift: '&#8593;',
    keyCode: 38,
    code: 'ArrowUp',
    class: 'arrowUp',
  },
  {
    keyEng: 'Shift',
    keyEngShift: 'Shift',
    keyRus: 'Shift',
    keyRusShift: 'Shift',
    keyCode: 16,
    code: 'ShiftRight',
    class: 'shiftRight',
  },
  {
    keyEng: 'Ctrl',
    keyEngShift: 'Ctrl',
    keyRus: 'Ctrl',
    keyRusShift: 'Ctrl',
    keyCode: 17,
    code: 'ControlLeft',
    class: 'controlLeft',
  },
  {
    keyEng: 'Alt',
    keyEngShift: 'Alt',
    keyRus: 'Alt',
    keyRusShift: 'Alt',
    keyCode: 18,
    code: 'AltLeft',
    class: 'altLeft',
  },
  {
    keyEng: ' ',
    keyEngShift: ' ',
    keyRus: ' ',
    keyRusShift: ' ',
    keyCode: 32,
    code: 'Space',
    class: 'space',
  },
  {
    keyEng: 'Alt',
    keyEngShift: 'Alt',
    keyRus: 'Alt',
    keyRusShift: 'Alt',
    keyCode: 18,
    code: 'AltRight',
    class: 'altRight',
  },
  {
    keyEng: '&#8592;',
    keyEngShift: '&#8592;',
    keyRus: '&#8592;',
    keyRusShift: '&#8592;',
    keyCode: 37,
    code: 'ArrowLeft',
    class: 'arrowLeft',
  },
  {
    keyEng: '&#8595;',
    keyEngShift: '&#8595;',
    keyRus: '&#8595;',
    keyRusShift: '&#8595;',
    keyCode: 40,
    code: 'ArrowDown',
    class: 'arrowDown',
  },
  {
    keyEng: '&#8594;',
    keyEngShift: '&#8594;',
    keyRus: '&#8594;',
    keyRusShift: '&#8594;',
    keyCode: 39,
    code: 'ArrowRight',
    class: 'arrowRight',
  },
  {
    keyEng: 'Ctrl',
    keyEngShift: 'Ctrl',
    keyRus: 'Ctrl',
    keyRusShift: 'Ctrl',
    keyCode: 17,
    code: 'ControlRight',
    class: 'controlRight',
  },
];

export default keys;
